- name: Kalliope caldav euron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: caldav
        version: 0.5.0
    - name: "Install package dependencies"
      apt:
        name: libxml2-dev libxslt1-dev
        state: present
